Assignment:	 
		g++ model.cpp -c -std=c++0x
		g++ controller.cpp -c
		g++ view.cpp -c
		g++ FastTrackball.c -c
		g++ FastTrackball.o controller.o view.o model.o Main.cpp -o  assignment4 -lSOIL -lglut -lGLU -lGL -std=c++0x

run:
		./assignment4 ../bin/tankbase.ply ../bin/tankhead.ply ../bin/victory-destroyer.ply ../bin/starship.ply
clear:
		rm -f assignment4
		rm -f *.o
